// Code generated by go-swagger; DO NOT EDIT.

// Package restapi The Neuro-PetStore
//
//	Schemes:
//	  http
//	Host: the-neuro-pet-store.com
//	BasePath: /v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
