// Code generated by go-swagger; DO NOT EDIT.

package pets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"theNeuroPetStore/api/models"
)

// PetsListOKCode is the HTTP code returned for type PetsListOK
const PetsListOKCode int = 200

/*
PetsListOK List of Pets

swagger:response petsListOK
*/
type PetsListOK struct {

	/*
	  In: Body
	*/
	Payload models.Pets `json:"body,omitempty"`
}

// NewPetsListOK creates PetsListOK with default headers values
func NewPetsListOK() *PetsListOK {

	return &PetsListOK{}
}

// WithPayload adds the payload to the pets list o k response
func (o *PetsListOK) WithPayload(payload models.Pets) *PetsListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pets list o k response
func (o *PetsListOK) SetPayload(payload models.Pets) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PetsListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Pets{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PetsListBadRequestCode is the HTTP code returned for type PetsListBadRequest
const PetsListBadRequestCode int = 400

/*
PetsListBadRequest Bad Request

swagger:response petsListBadRequest
*/
type PetsListBadRequest struct {
}

// NewPetsListBadRequest creates PetsListBadRequest with default headers values
func NewPetsListBadRequest() *PetsListBadRequest {

	return &PetsListBadRequest{}
}

// WriteResponse to the client
func (o *PetsListBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PetsListNotFoundCode is the HTTP code returned for type PetsListNotFound
const PetsListNotFoundCode int = 404

/*
PetsListNotFound Pets Not Found

swagger:response petsListNotFound
*/
type PetsListNotFound struct {
}

// NewPetsListNotFound creates PetsListNotFound with default headers values
func NewPetsListNotFound() *PetsListNotFound {

	return &PetsListNotFound{}
}

// WriteResponse to the client
func (o *PetsListNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PetsListInternalServerErrorCode is the HTTP code returned for type PetsListInternalServerError
const PetsListInternalServerErrorCode int = 500

/*
PetsListInternalServerError Server Error

swagger:response petsListInternalServerError
*/
type PetsListInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPetsListInternalServerError creates PetsListInternalServerError with default headers values
func NewPetsListInternalServerError() *PetsListInternalServerError {

	return &PetsListInternalServerError{}
}

// WithPayload adds the payload to the pets list internal server error response
func (o *PetsListInternalServerError) WithPayload(payload string) *PetsListInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pets list internal server error response
func (o *PetsListInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PetsListInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
