// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Pet pet
//
// swagger:model Pet
type Pet struct {

	// Id
	ID int64 `json:"Id,omitempty"`

	// image Url
	ImageURL string `json:"ImageUrl,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// qualities
	Qualities []string `json:"Qualities"`

	// species
	Species string `json:"Species,omitempty"`
}

// Validate validates this pet
func (m *Pet) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pet based on context it is used
func (m *Pet) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Pet) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Pet) UnmarshalBinary(b []byte) error {
	var res Pet
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
